include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
    prefer_const_constructors_in_immutables: false
    avoid_unnecessary_containers: false
    sized_box_for_whitespace: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore